In [1]:
import pandas as pd 
import numpy as np 
import time

from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Read csv
df = pd.read_csv('D:\EE551\\heart_2020_cleaned.csv')

In [3]:
starttime=time.time()

# Data processing
for i in df.HeartDisease.values:
    if i  == 'No':
        df.HeartDisease.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.HeartDisease.replace(i, 1, inplace = True)
    
for i in df.Smoking.values:
    if i  == 'No':
        df.Smoking.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.Smoking.replace(i, 1, inplace = True)
        
for i in df.AlcoholDrinking.values:
    if i  == 'No':
        df.AlcoholDrinking.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.AlcoholDrinking.replace(i, 1, inplace = True)        

for i in df.Stroke.values:
    if i  == 'No':
        df.Stroke.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.Stroke.replace(i, 1, inplace = True)

for i in df.DiffWalking.values:
    if i  == 'No':
        df.DiffWalking.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.DiffWalking.replace(i, 1, inplace = True)        

for i in df.Sex.values:
    if i  == 'Female':
        df.Sex.replace(i, 0, inplace = True)
    elif i == 'Male':
        df.Sex.replace(i, 1, inplace = True)        

for i in df.AgeCategory.values:
    if i  == '18-24':
        df.AgeCategory.replace(i, 0, inplace = True)
    elif i == '25-29':
        df.AgeCategory.replace(i, 1/12, inplace = True)
    elif i == '30-34':
        df.AgeCategory.replace(i, 2/12, inplace = True)    
    elif i == '35-39':
        df.AgeCategory.replace(i, 3/12, inplace = True)
    elif i == '40-44':
        df.AgeCategory.replace(i, 4/12, inplace = True) 
    elif i == '45-49':
        df.AgeCategory.replace(i, 5/12, inplace = True)
    elif i == '50-54':
        df.AgeCategory.replace(i, 6/12, inplace = True)
    elif i == '55-59':
        df.AgeCategory.replace(i, 7/12, inplace = True)
    elif i == '60-64':
        df.AgeCategory.replace(i, 8/12, inplace = True) 
    elif i == '65-69':
        df.AgeCategory.replace(i, 9/12, inplace = True)
    elif i == '70-74':
        df.AgeCategory.replace(i, 10/12, inplace = True)
    elif i == '75-79':
        df.AgeCategory.replace(i, 11/12, inplace = True)
    elif i == '80 or older':
        df.AgeCategory.replace(i, 1, inplace = True)    
        
for i in df.PhysicalActivity.values:
    if i  == 'No':
        df.PhysicalActivity.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.PhysicalActivity.replace(i, 1, inplace = True)        

for i in df.Diabetic.values:
    if i  == 'No':
        df.Diabetic.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.Diabetic.replace(i, 1, inplace = True)
    elif i == 'No, borderline diabetes':
        df.Diabetic.replace(i, 1/3, inplace = True)    
    elif i == 'Yes (during pregnancy)':
        df.Diabetic.replace(i, 2/3, inplace = True)    

        
for i in df.GenHealth.values:
    if i  == 'Excellent':
        df.GenHealth.replace(i, 1, inplace = True)
    elif i == 'Very good':
        df.GenHealth.replace(i, 0.75, inplace = True)
    elif i == 'Good':
        df.GenHealth.replace(i, 0.5, inplace = True)    
    elif i == 'Fair':
        df.GenHealth.replace(i, 0.25, inplace = True)
    elif i == 'Poor':
        df.GenHealth.replace(i, 0, inplace = True)    
        
for i in df.Asthma.values:
    if i  == 'No':
        df.Asthma.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.Asthma.replace(i, 1, inplace = True) 
        
for i in df.KidneyDisease.values:
    if i  == 'No':
        df.KidneyDisease.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.KidneyDisease.replace(i, 1, inplace = True)      
        
for i in df.SkinCancer.values:
    if i  == 'No':
        df.SkinCancer.replace(i, 0, inplace = True)
    elif i == 'Yes':
        df.SkinCancer.replace(i, 1, inplace = True)      
        
for i in df.Race.values:
    if i  == 'White':
        df.Race.replace(i, 0, inplace = True)
    elif i == 'Hispanic':
        df.Race.replace(i, 1/5, inplace = True)
    elif i == 'Black':
        df.Race.replace(i, 2/5, inplace = True)    
    elif i == 'Asian':
        df.Race.replace(i, 3/5, inplace = True)
    elif i == 'American Indian/Alaskan Native':
        df.Race.replace(i, 4/5, inplace = True) 
    elif i == 'Other':
        df.Race.replace(i, 1, inplace = True)

endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

Program running time: 1.9036705493927002 s


In [15]:
# Check the data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   HeartDisease      319795 non-null  float64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  float64
 3   AlcoholDrinking   319795 non-null  float64
 4   Stroke            319795 non-null  float64
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  float64
 8   Sex               319795 non-null  float64
 9   AgeCategory       319795 non-null  float64
 10  Race              319795 non-null  float64
 11  Diabetic          319795 non-null  float64
 12  PhysicalActivity  319795 non-null  float64
 13  GenHealth         319795 non-null  float64
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  float64
 16  KidneyDisease     31

In [16]:
# Data normalize
df = (df-df.min())/(df.max()-df.min())
df.describe()

HeartDisease            BMI        Smoking  AlcoholDrinking  \
count  319795.000000  319795.000000  319795.000000    319795.000000   
mean        0.085595       0.196854       0.412477         0.068097   
std         0.279766       0.076737       0.492281         0.251912   
min         0.000000       0.000000       0.000000         0.000000   
25%         0.000000       0.144996       0.000000         0.000000   
50%         0.000000       0.184957       0.000000         0.000000   
75%         0.000000       0.234215       1.000000         0.000000   
max         1.000000       1.000000       1.000000         1.000000   

              Stroke  PhysicalHealth   MentalHealth    DiffWalking  \
count  319795.000000   319795.000000  319795.000000  319795.000000   
mean        0.037740        0.112390       0.129946       0.138870   
std         0.190567        0.265028       0.265175       0.345812   
min         0.000000        0.000000       0.000000       0.000000   
25%         0.000000        0.000000       0.000000       0.000000   
50%         0.000000        0.000000       0.000000       0.000000   
75%         0.000000        0.066667       0.100000       0.000000   
max         1.000000        1.000000       1.000000       1.000000   

                 Sex    AgeCategory           Race       Diabetic  \
count  319795.000000  319795.000000  319795.000000  319795.000000   
mean        0.475273       0.542878       0.108179       0.139991   
std         0.499389       0.297063       0.238479       0.337496   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.333333       0.000000       0.000000   
50%         0.000000       0.583333       0.000000       0.000000   
75%         1.000000       0.750000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

       PhysicalActivity      GenHealth      SleepTime         Asthma  \
count     319795.000000  319795.000000  319795.000000  319795.000000   
mean           0.775362       0.648757       0.265090       0.134061   
std            0.417344       0.260730       0.062435       0.340718   
min            0.000000       0.000000       0.000000       0.000000   
25%            1.000000       0.500000       0.217391       0.000000   
50%            1.000000       0.750000       0.260870       0.000000   
75%            1.000000       0.750000       0.304348       0.000000   
max            1.000000       1.000000       1.000000       1.000000   

       KidneyDisease     SkinCancer  
count  319795.000000  319795.000000  
mean        0.036833       0.093244  
std         0.188352       0.290775  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000

In [5]:
# Independent variable
X = df[['BMI', 'Smoking', 'AlcoholDrinking','Stroke'
        ,'PhysicalHealth','MentalHealth','DiffWalking','Sex'
        ,'AgeCategory','Diabetic','Race','PhysicalActivity','GenHealth'
        ,'SleepTime','Asthma','KidneyDisease','SkinCancer']].values
# Dependent variable
Y = df[ 'HeartDisease'].values
# Take a random 70% samples for training and the rest 30% for test
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size = 0.3, random_state = 0)

In [9]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

starttime=time.time()
NB_Bernoulli=BernoulliNB()
NB_Bernoulli.fit(Xtrain,Ytrain)
NB_Bernoullipred=NB_Bernoulli.predict(Xtest)
# print(confusion_matrix(Ytest,NB_Bernoullipred ))
print("BernoulliNB Accuracy : ", accuracy_score(Ytest,NB_Bernoullipred))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

starttime=time.time()
NB_Gaussian=GaussianNB()
NB_Gaussian.fit(Xtrain,Ytrain)
NB_Gaussianpred=NB_Gaussian.predict(Xtest)
# print(confusion_matrix(Ytest,NB_Gaussianpred))
print("\nGaussianNB Accuracy : ", accuracy_score(Ytest,NB_Gaussianpred ))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

starttime=time.time()
NB_Multinomial=MultinomialNB()
NB_Multinomial.fit(Xtrain,Ytrain)
NB_Multinomialpred=NB_Multinomial.predict(Xtest)
# print(confusion_matrix(Ytest,NB_Multinomialpred))
print("\nMultinomialNB Accuracy : ", accuracy_score(NB_Multinomialpred, Ytest))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

BernoulliNB Accuracy :  0.8977683736540927
Program running time: 0.14334344863891602 s

GaussianNB Accuracy :  0.8428063665454091
Program running time: 0.20087933540344238 s

MultinomialNB Accuracy :  0.9126424081968751
Program running time: 0.05356788635253906 s


In [10]:
from sklearn.linear_model import LogisticRegression

starttime=time.time()
LR = LogisticRegression(random_state = 0, max_iter=300)
LR.fit(Xtrain, Ytrain)
LRpred = LR.predict(Xtest)
print(confusion_matrix(Ytest, LRpred))
print ("Accuracy : ", accuracy_score(Ytest, LRpred))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

[[86975   755]
 [ 7357   852]]
Accuracy :  0.9154462731527324
Program running time: 1.1439664363861084 s


In [11]:
from sklearn.tree import DecisionTreeClassifier  

starttime=time.time()
DecisionTree=DecisionTreeClassifier(criterion='entropy', max_leaf_nodes=498)
DecisionTree.fit(Xtrain, Ytrain)
DecisionTreepred =DecisionTree.predict(Xtest)
print(confusion_matrix(Ytest, DecisionTreepred))
print(accuracy_score(Ytest, DecisionTreepred))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

[[87105   625]
 [ 7532   677]]
0.9149772251117898
Program running time: 0.8678891658782959 s


In [12]:
from sklearn.ensemble import RandomForestClassifier

starttime=time.time()
RrandomForest=RandomForestClassifier()
RrandomForest.fit(Xtrain, Ytrain)
RrandomForestpred = RrandomForest.predict(Xtest)
print(confusion_matrix(Ytest, RrandomForestpred))
print(accuracy_score(Ytest, RrandomForestpred))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

[[86043  1687]
 [ 7228   981]]
0.9070763714443553
Program running time: 26.313808917999268 s


In [13]:
from sklearn.neural_network import MLPClassifier

starttime=time.time()
ANN = MLPClassifier(hidden_layer_sizes=(30,30), 
                    activation='logistic', 
                    solver='adam',
                    learning_rate_init=0.001, 
                    random_state=0)
ANN.fit(Xtrain, Ytrain)
ANNpred = ANN.predict(Xtest)
print(confusion_matrix(Ytest, ANNpred))
print(accuracy_score(Ytest, ANNpred))
endtime=time.time()
runtime=endtime-starttime
print('Program running time:',runtime,'s')

[[87203   527]
 [ 7520   689]]
0.9161237869896497
Program running time: 33.36961054801941 s
